// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqldZoEiuFR2aSw7kCda6NHqcvEFStv7g',
    appId: '1:842671585755:web:e96b35ef68deb7ce208ffe',
    messagingSenderId: '842671585755',
    projectId: 'jomla-platform',
    authDomain: 'jomla-platform.firebaseapp.com',
    storageBucket: 'jomla-platform.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB4oyLTxP3v2DQDAI9UXe4HNbRzdrwwHA',
    appId: '1:842671585755:android:e579354648a54530208ffe',
    messagingSenderId: '842671585755',
    projectId: 'jomla-platform',
    storageBucket: 'jomla-platform.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD84wxeV6YkucBtf25bFd6RCgicuSgxdyA',
    appId: '1:842671585755:ios:955145d80dc32393208ffe',
    messagingSenderId: '842671585755',
    projectId: 'jomla-platform',
    storageBucket: 'jomla-platform.appspot.com',
    iosClientId: '842671585755-gtm8fon6d7grtsuafu0gdhuc0c95itf8.apps.googleusercontent.com',
    iosBundleId: 'com.example.jomla',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD84wxeV6YkucBtf25bFd6RCgicuSgxdyA',
    appId: '1:842671585755:ios:955145d80dc32393208ffe',
    messagingSenderId: '842671585755',
    projectId: 'jomla-platform',
    storageBucket: 'jomla-platform.appspot.com',
    iosClientId: '842671585755-gtm8fon6d7grtsuafu0gdhuc0c95itf8.apps.googleusercontent.com',
    iosBundleId: 'com.example.jomla',
  );
}
